# Generated by Django 3.2.5 on 2021-07-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoredSession',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('properties', models.JSONField()),
                ('content', models.JSONField()),
                ('data', models.BinaryField()),
            ],
            options={
                'db_table': 'storedsessions',
            },
        ),
    ]
