# Generated by Django 3.2.5 on 2021-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_storedsession_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storedsession',
            name='content',
        ),
        migrations.AlterField(
            model_name='storedsession',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
