# Generated by Django 3.2.5 on 2021-07-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_storedsession_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedsession',
            name='data',
            field=models.JSONField(),
        ),
    ]
